/// Patient Management Menu Implementation
import 'package:hospital_management/domain/entities/patient.dart';
import 'package:hospital_management/domain/repositories/patient_repository.dart';
import 'package:hospital_management/domain/repositories/doctor_repository.dart';
import 'package:hospital_management/domain/repositories/room_repository.dart';
import 'package:hospital_management/domain/usecases/patient/admit_patient.dart';
import 'package:hospital_management/presentation/menus/base_menu.dart';
import 'package:hospital_management/presentation/utils/input_validator.dart';
import 'package:hospital_management/presentation/utils/ui_helper.dart';
import 'dart:io';

class PatientMenu extends BaseMenu {
  final PatientRepository _patientRepository;
  final DoctorRepository _doctorRepository;
  final RoomRepository _roomRepository;

  PatientMenu({
    required PatientRepository patientRepository,
    required DoctorRepository doctorRepository,
    required RoomRepository roomRepository,
  })  : _patientRepository = patientRepository,
        _doctorRepository = doctorRepository,
        _roomRepository = roomRepository;

  @override
  String get menuTitle => 'PATIENT MANAGEMENT';

  @override
  List<String> get menuOptions => [
        'View All Patients',
        'Search Patient by ID',
        'Admit New Patient',
        'Update Patient',
        'Discharge Patient',
        'Assign Doctor',
        'Schedule Meeting',
        'View Patient Details',
        'View Patients by Doctor',
        'View Patients by Blood Type',
        'View Patients with Upcoming Meetings',
      ];

  @override
  Future<void> handleChoice(int choice) async {
    switch (choice) {
      case 1:
        await _viewAllPatients();
        break;
      case 2:
        await _searchPatientById();
        break;
      case 3:
        await _admitNewPatient();
        break;
      case 4:
        await _updatePatient();
        break;
      case 5:
        await _dischargePatient();
        break;
      case 6:
        await _assignDoctor();
        break;
      case 7:
        await _scheduleMeeting();
        break;
      case 8:
        await _viewPatientDetails();
        break;
      case 9:
        await _viewPatientsByDoctor();
        break;
      case 10:
        await _viewPatientsByBloodType();
        break;
      case 11:
        await _viewPatientsWithUpcomingMeetings();
        break;
    }
  }

  Future<void> _viewAllPatients() async {
    UIHelper.printHeader('All Patients');

    final patients = await _patientRepository.getAllPatients();
    if (patients.isEmpty) {
      UIHelper.printWarning('No patients found');
      return;
    }

    final tableData = patients
        .map((patient) => [
              patient.patientID,
              patient.name,
              patient.bloodType,
              patient.dateOfBirth,
              patient.assignedDoctors.map((d) => d.name).join(', '),
            ])
        .toList();

    UIHelper.printTable(
      tableData,
      headers: ['ID', 'Name', 'Blood Type', 'DOB', 'Doctors'],
    );
  }

  Future<void> _searchPatientById() async {
    UIHelper.printHeader('Search Patient by ID');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final patient = await _patientRepository.getPatientById(patientId);

    _displayPatientDetails(patient);
  }

  Future<void> _admitNewPatient() async {
    UIHelper.printHeader('Admit New Patient');

    final name = InputValidator.readString('Enter patient name');
    final dob = InputValidator.readDate('Enter date of birth');
    final bloodType = InputValidator.readBloodType('Enter blood type');
    final address = InputValidator.readString('Enter address');
    final tel = InputValidator.readPhone('Enter phone number');
    final emergencyContact =
        InputValidator.readString('Enter emergency contact name');

    // Create patient object (ID will be auto-generated by repository)
    final patient = Patient(
      name: name,
      dateOfBirth: dob.toIso8601String(),
      address: address,
      tel: tel,
      patientID: 'AUTO', // Placeholder - will be auto-generated
      bloodType: bloodType,
      medicalRecords: [],
      allergies: [],
      emergencyContact: emergencyContact,
    );

    // Get available room and bed
    UIHelper.printSubHeader('Room Assignment');
    final roomId = InputValidator.readString('Enter room ID (e.g. R101)');
    final bedNumber = InputValidator.readString('Enter bed number (e.g. B1)');

    // Execute admission
    await AdmitPatient(
      patientRepository: _patientRepository,
      roomRepository: _roomRepository,
    ).execute(
      patient: patient,
      roomId: roomId,
      bedNumber: bedNumber,
    );

    UIHelper.printSuccess(
        'Patient admitted successfully with ID: ${patient.patientID}');
  }

  Future<void> _updatePatient() async {
    UIHelper.printHeader('Update Patient');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final patient = await _patientRepository.getPatientById(patientId);

    UIHelper.printInfo('Current patient details:');
    _displayPatientDetails(patient);

    final name = InputValidator.readString(
        'Enter new name (or press Enter to keep current)',
        allowEmpty: true);
    final address = InputValidator.readString(
        'Enter new address (or press Enter to keep current)',
        allowEmpty: true);
    final tel = InputValidator.readString(
        'Enter new phone (or press Enter to keep current)',
        allowEmpty: true);
    final emergencyContact = InputValidator.readString(
        'Enter new emergency contact (or press Enter to keep current)',
        allowEmpty: true);

    if (name.isNotEmpty ||
        address.isNotEmpty ||
        tel.isNotEmpty ||
        emergencyContact.isNotEmpty) {
      final updated = Patient(
        patientID: patient.patientID,
        name: name.isNotEmpty ? name : patient.name,
        dateOfBirth: patient.dateOfBirth,
        address: address.isNotEmpty ? address : patient.address,
        tel: tel.isNotEmpty ? tel : patient.tel,
        bloodType: patient.bloodType,
        medicalRecords: patient.medicalRecords.toList(),
        allergies: patient.allergies.toList(),
        emergencyContact: emergencyContact.isNotEmpty
            ? emergencyContact
            : patient.emergencyContact,
      );

      await _patientRepository.updatePatient(updated);
      UIHelper.printSuccess('Patient updated successfully');
    } else {
      UIHelper.printInfo('No changes made');
    }
  }

  Future<void> _dischargePatient() async {
    UIHelper.printHeader('Discharge Patient');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final patient = await _patientRepository.getPatientById(patientId);

    if (patient.currentRoom == null) {
      UIHelper.printWarning('Patient is not currently admitted to a room');
      return;
    }

    // Discharge patient from room/bed
    patient.discharge();

    // Update patient record
    await _patientRepository.updatePatient(patient);

    UIHelper.printSuccess('Patient discharged successfully');
  }

  Future<void> _assignDoctor() async {
    UIHelper.printHeader('Assign Doctor to Patient');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final doctorId = InputValidator.readId('Enter doctor ID', 'D');

    final patient = await _patientRepository.getPatientById(patientId);
    final doctor = await _doctorRepository.getDoctorById(doctorId);

    patient.assignDoctor(doctor);
    await _patientRepository.updatePatient(patient);

    UIHelper.printSuccess('Doctor assigned successfully');
  }

  Future<void> _scheduleMeeting() async {
    UIHelper.printHeader('Schedule Patient Meeting');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final doctorId = InputValidator.readId('Enter doctor ID', 'D');

    final patient = await _patientRepository.getPatientById(patientId);
    final doctor = await _doctorRepository.getDoctorById(doctorId);

    // Validate doctor assignment
    if (!patient.assignedDoctors.contains(doctor)) {
      UIHelper.printError(
          'Doctor must be assigned to patient before scheduling meetings');
      return;
    }

    // Get date and time
    final date = InputValidator.readDate('Enter meeting date');
    final time = InputValidator.readTime('Enter meeting time');

    // Parse time components
    final timeComponents = time.split(':');
    final meetingDate = DateTime(
      date.year,
      date.month,
      date.day,
      int.parse(timeComponents[0]),
      int.parse(timeComponents[1]),
    );

    try {
      // Schedule meeting using Patient entity method
      patient.scheduleNextMeeting(
        doctor: doctor,
        meetingDate: meetingDate,
      );

      // Update patient record
      await _patientRepository.updatePatient(patient);

      UIHelper.printSuccess('Meeting scheduled successfully');
    } catch (e) {
      UIHelper.printError('Failed to schedule meeting: $e');
    }
  }

  Future<void> _viewPatientDetails() async {
    UIHelper.printHeader('View Patient Details');

    final patientId = InputValidator.readId('Enter patient ID', 'P');
    final patient = await _patientRepository.getPatientById(patientId);

    _displayPatientDetails(patient);
  }

  Future<void> _viewPatientsByDoctor() async {
    UIHelper.printHeader('View Patients by Doctor');

    final doctorId = InputValidator.readId('Enter doctor ID', 'D');
    final patients = await _patientRepository.getPatientsByDoctorId(doctorId);

    if (patients.isEmpty) {
      UIHelper.printWarning('No patients found for this doctor');
      return;
    }

    final tableData = patients
        .map((patient) => [
              patient.patientID,
              patient.name,
              patient.bloodType,
              patient.dateOfBirth,
              patient.nextMeetingInfo ?? 'No meeting scheduled',
            ])
        .toList();

    UIHelper.printTable(
      tableData,
      headers: ['ID', 'Name', 'Blood Type', 'DOB', 'Next Meeting'],
    );
  }

  Future<void> _viewPatientsByBloodType() async {
    UIHelper.printHeader('View Patients by Blood Type');

    final bloodType = InputValidator.readBloodType('Enter blood type');
    final patients = await _patientRepository.getPatientsByBloodType(bloodType);

    if (patients.isEmpty) {
      UIHelper.printWarning('No patients found with blood type $bloodType');
      return;
    }

    final tableData = patients
        .map((patient) => [
              patient.patientID,
              patient.name,
              patient.dateOfBirth,
              patient.tel,
              patient.currentRoom?.number ?? 'Not admitted',
            ])
        .toList();

    UIHelper.printTable(
      tableData,
      headers: ['ID', 'Name', 'DOB', 'Phone', 'Room'],
    );
  }

  Future<void> _viewPatientsWithUpcomingMeetings() async {
    UIHelper.printHeader('Patients with Upcoming Meetings');

    final patients = await _patientRepository.getPatientsWithUpcomingMeetings();

    if (patients.isEmpty) {
      UIHelper.printWarning('No patients have upcoming meetings');
      return;
    }

    final tableData = patients
        .map((patient) => [
              patient.patientID,
              patient.name,
              patient.nextMeetingInfo ?? 'Error: Missing meeting info',
              patient.nextMeetingDoctor?.name ?? 'Unknown Doctor',
            ])
        .toList();

    UIHelper.printTable(
      tableData,
      headers: ['ID', 'Name', 'Meeting Info', 'Doctor'],
    );
  }

  void _displayPatientDetails(Patient patient) {
    UIHelper.printSubHeader('Patient Information');
    print('ID: ${patient.patientID}');
    print('Name: ${patient.name}');
    print('DOB: ${UIHelper.formatDate(DateTime.parse(patient.dateOfBirth))}');
    print('Blood Type: ${patient.bloodType}');
    print('Address: ${patient.address}');
    print('Phone: ${patient.tel}');
    print('Emergency Contact: ${patient.emergencyContact}');

    if (patient.assignedDoctors.isNotEmpty) {
      UIHelper.printSubHeader('Assigned Doctors');
      for (final doctor in patient.assignedDoctors) {
        print('• ${doctor.name}');
      }
    }

    if (patient.hasNextMeeting) {
      UIHelper.printSubHeader('Next Meeting');
      print(patient.nextMeetingInfo);

      if (patient.isNextMeetingSoon) {
        UIHelper.printWarning('Meeting is within the next 7 days');
      } else if (patient.isNextMeetingOverdue) {
        UIHelper.printError('Meeting is overdue');
      }
    }

    if (patient.currentRoom != null) {
      UIHelper.printSubHeader('Current Admission');
      print('Room: ${patient.currentRoom!.number}');
      if (patient.currentBed != null) {
        print('Bed: ${patient.currentBed!.bedNumber}');
      }
    }

    if (patient.medicalRecords.isNotEmpty) {
      UIHelper.printSubHeader('Recent Medical Records');
      for (final record in patient.medicalRecords.take(5)) {
        print('• $record');
      }
    }

    if (patient.allergies.isNotEmpty) {
      UIHelper.printSubHeader('Allergies');
      for (final allergy in patient.allergies) {
        print('• $allergy');
      }
    }
  }
}
